# Generated by Django 5.0.6 on 2024-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_program", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdffile",
            name="file",
            field=models.FileField(upload_to="pdfs/"),
        ),
    ]
