# Generated by Django 5.0.6 on 2024-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_tests", "0002_remove_question_correct_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
