# Generated by Django 5.0.6 on 2024-06-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_tests", "0004_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="name",
            field=models.CharField(default="Аноним", max_length=100),
            preserve_default=False,
        ),
    ]
