# Generated by Django 5.0.6 on 2024-06-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_lecture_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
