# Generated by Django 5.0.6 on 2024-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labworks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labwork",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AlterField(
            model_name="labwork",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
