# Generated by Django 5.0.6 on 2024-06-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labworks", "0003_labwork_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labwork",
            old_name="image",
            new_name="image1",
        ),
        migrations.AddField(
            model_name="labwork",
            name="image2",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image3",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image4",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image5",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image6",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
    ]
