# Generated by Django 5.0.6 on 2024-06-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labworks", "0004_rename_image_labwork_image1_labwork_image2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labwork",
            name="description",
        ),
    ]
