# Generated by Django 5.0.6 on 2024-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labworks", "0005_remove_labwork_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="labwork",
            name="image10",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image11",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image12",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image13",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image14",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image15",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image7",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image8",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
        migrations.AddField(
            model_name="labwork",
            name="image9",
            field=models.FileField(blank=True, null=True, upload_to="labwork_images/"),
        ),
    ]
