# Generated by Django 5.0.6 on 2024-06-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labworks", "0006_labwork_image10_labwork_image11_labwork_image12_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labwork",
            name="image11",
        ),
        migrations.RemoveField(
            model_name="labwork",
            name="image12",
        ),
        migrations.RemoveField(
            model_name="labwork",
            name="image13",
        ),
        migrations.RemoveField(
            model_name="labwork",
            name="image14",
        ),
        migrations.RemoveField(
            model_name="labwork",
            name="image15",
        ),
    ]
